### ISSUE TITLE
How does this code set the number of Bootstrap Samples B?

### ISSUE THREAD

**Issue by laurenleesc** [zjohn77/buckshotpp#2]
Hi,

I cannot seem to understand how or where your code sets the number of Bootstrap samples?

Thanks!

**Comment by zjohn77** [comment]
Please look in this file here for a method called **__resample**: [buckshotpp/__init__.py](https://github.com/zjohn77/buckshotpp/blob/master/buckshotpp/__init__.py)

The snippet below shows what the __resample method looks like in that file, and you can see that the NUM_BOOTSTRAPS function argument defines the number of bootstrap samples and it defaults to 3.
`    def __resample(self, df, NUM_BOOTSTRAPS = 3):
        '''take 3 bootstrap sub-samples for faster, bagged kmeans fits'''        
        bootstraps = [None] * NUM_BOOTSTRAPS
        for bootI in range(NUM_BOOTSTRAPS):  
            bootstraps[bootI] = df.sample(frac=1/NUM_BOOTSTRAPS, replace=True)
        return bootstraps`

**Comment by laurenleesc** [comment]
Thank you!
